{
	"countries":["US","CA","MX"],
	"ebatesBuyers":{"US":{
			"email":"usebates@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"usebates*",
			"type":"EbatesBuyer"
		},"CA":{
			"email":"caebates@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"caebates*",
			"type":"EbatesBuyer"
		},"MX":{
			"email":"mxebates@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"mxebates*",
			"type":"EbatesBuyer"
		}
	},
	"giftCardBuyers":{},
	"googledrivebooks":{"US":"https://docs.google.com/spreadsheets/d/1IMbmaLUjqvZ7w8OdPd59fpTuad8U__5PAyKg3yR0DjY/edit#gid=1901579832","CA":"https://docs.google.com/spreadsheets/d/1VIar2m0_78mUk3wcmfiqLWQOBB34NBsac94R4EYgcOU/edit#gid=2088174895","MX":""
	},
	"googledriveproducts":{"US":"","CA":"https://docs.google.com/spreadsheets/d/19pVN9f9ayfBiyMpdRpLsCmZlSjh8dYGDVgYihFFUcqU/edit#gid=730979804","MX":"https://docs.google.com/spreadsheets/d/19pVN9f9ayfBiyMpdRpLsCmZlSjh8dYGDVgYihFFUcqU/edit#gid=1279259393"
	},
	"id":"714",
	"orderFinders":{"US":"Jane","CA":"MikeB","MX":"Anny"
	},
	"primeBuyers":{"US":{
			"email":"pbuyerus@gmail.com",
            "enable2StepVerfication":false,
            "isPrimeAvailable":false,
            "name":"",
            "password":"pbuyeruspw",
			"type":"PrimeBuyer"
		},"CA":{
			"email":"caprimebuyer@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"caprimebuyer*",
			"type":"PrimeBuyer"
		},"MX":{

		}
	},
	"prodPrimeBuyers":{"US":"",
	    "CA":{
			"email":"caprodPrimeBuyer@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"ZeroTemple*",
			"type":"PrimeBuyer"
		},"MX":{
			"email":"mxprodPrimeBuyer@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"ZeroTemple*",
			"type":"PrimeBuyer"
		}
	},
	"prodPtBuyers":{"US":{

		},"CA":{
			"email":"caprodPtBuyers@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"ZeroTemple*",
			"type":"PtBuyer"
		},"MX":{
			"email":"mxprobuyer@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"mxprobuyer*",
			"type":"PtBuyer"
		}
	},
	"ptBuyers":{"US":{
			"email":"buyerus@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"buyeruspw",
			"type":"PtBuyer"
		},"CA":{
			"email":"captBuyers@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"ZeroTemple*",
			"type":"PtBuyer"
		},"MX":{

		}
	},
	"sellerEmails":{"US":{
			"email":"usselleremail@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"Mike Pro",
			"password":"BarrP78Fly",
			"type":"EmailSender"
		},"CA":{
			"email":"caselleremail@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"Mike Pro",
			"password":"BarrP78Fly",
			"type":"EmailSender"
		},"MX":{
			"email":"mxselleremail@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"Mike Pro",
			"password":"BarrP78Fly",
			"type":"EmailSender"
		}
	},
	"sellerids":{"US":"A3BEPQLI451F6I/tATVPDKIKX0DER/tAKIAI73MGXM4FSWB6TIQ/tW5oIE4cbQ1MTG3YO5h4JU93J7FGjDX1/OLDjADBc/tMike Pro/t1.0/tnull","CA":"CAA3BEPQLI451F6I/tCAATVPDKIKX0DER/tCAAKIAI73MGXM4FSWB6TIQ/tCAW5oIE4cbQ1MTG3YO5h4JU93J7FGjDX1/OLDjADBc/tMike Pro/t1.0/tnull","MX":""
	},
	"sellers":{"US":{
			"email":"usseller@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"BarrP78Fly",
			"type":"Seller"
		},"CA":{
			"email":"caseller@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"BarrP78Fly",
			"type":"Seller"
		},"MX":{
			"email":"caseller@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"BarrP78Fly",
			"type":"Seller"
		}
	},
	"signatures":{"US":"Mike","CA":"Mike","MX":"Mike"
	},
	"sortNo":1
}