{
	"countries":["US","CA","MX"],
	"ebatesBuyers":{"US":{
			"email":"vagimike0@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"ZeroTemple*",
			"type":"EbatesBuyer"
		},"CA":{
			"email":"vagimike0@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"ZeroTemple*",
			"type":"EbatesBuyer"
		},"MX":{
			"email":"vagimike0@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"ZeroTemple*",
			"type":"EbatesBuyer"
		}
	},
	"giftCardBuyers":{},
	"googledrivebooks":{"US":"https://docs.google.com/spreadsheets/d/1IMbmaLUjqvZ7w8OdPd59fpTuad8U__5PAyKg3yR0DjY/edit#gid=1901579832","CA":"https://docs.google.com/spreadsheets/d/1VIar2m0_78mUk3wcmfiqLWQOBB34NBsac94R4EYgcOU/edit#gid=2088174895","MX":""
	},
	"googledriveproducts":{"US":"","CA":"https://docs.google.com/spreadsheets/d/19pVN9f9ayfBiyMpdRpLsCmZlSjh8dYGDVgYihFFUcqU/edit#gid=730979804","MX":"https://docs.google.com/spreadsheets/d/19pVN9f9ayfBiyMpdRpLsCmZlSjh8dYGDVgYihFFUcqU/edit#gid=1279259393"
	},
	"id":"714",
	"orderFinders":{"US":"Jane","CA":"MikeB","MX":"Anny"
	},
	"primeBuyers":{"US":{
			"email":"vagimike0@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"ZeroTemple*",
			"type":"PrimeBuyer"
		},"CA":{
			"email":"vagimike0@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"ZeroTemple*",
			"type":"PrimeBuyer"
		},"MX":{
			"email":"vagimike0@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"ZeroTemple*",
			"type":"PrimeBuyer"
		}
	},
	"prodPrimeBuyers":{"US":{
			"email":"vagimike0@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"ZeroTemple*",
			"type":"PrimeBuyer"
		},"CA":{
			"email":"vagimike0@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"ZeroTemple*",
			"type":"PrimeBuyer"
		},"MX":{
			"email":"vagimike0@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"ZeroTemple*",
			"type":"PrimeBuyer"
		}
	},
	"prodPtBuyers":{"US":{
			"email":"vagimike0@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"ZeroTemple*",
			"type":"PtBuyer"
		},"CA":{
			"email":"vagimike0@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"ZeroTemple*",
			"type":"PtBuyer"
		},"MX":{
			"email":"vagimike0@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"ZeroTemple*",
			"type":"PtBuyer"
		}
	},
	"ptBuyers":{"US":{
			"email":"vagimike0@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"ZeroTemple*",
			"type":"PtBuyer"
		},"CA":{
			"email":"vagimike0@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"ZeroTemple*",
			"type":"PtBuyer"
		},"MX":{
			"email":"vagimike0@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"ZeroTemple*",
			"type":"PtBuyer"
		}
	},
	"sellerEmails":{"US":{
			"email":"mike.barrpro@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"Mike Pro",
			"password":"BarrP78Fly",
			"type":"EmailSender"
		},"CA":{
			"email":"mike.barrpro@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"Mike Pro",
			"password":"BarrP78Fly",
			"type":"EmailSender"
		},"MX":{
			"email":"mike.barrpro@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"Mike Pro",
			"password":"BarrP78Fly",
			"type":"EmailSender"
		}
	},
	"sellerids":{"US":"A3BEPQLI451F6I/tATVPDKIKX0DER/tAKIAI73MGXM4FSWB6TIQ/tW5oIE4cbQ1MTG3YO5h4JU93J7FGjDX1/OLDjADBc/tMike Pro/t1.0/tnull","CA":"","MX":""
	},
	"sellers":{"US":{
			"email":"mike.barrpro@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"BarrP78Fly",
			"type":"Seller"
		},"CA":{
			"email":"mike.barrpro@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"BarrP78Fly",
			"type":"Seller"
		},"MX":{
			"email":"mike.barrpro@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"BarrP78Fly",
			"type":"Seller"
		}
	},
	"signatures":{"US":"Mike","CA":"Mike","MX":"Mike"
	},
	"sortNo":1
}