{
	"countries":["US","CA","UK","MX"],
	"ebatesBuyers":{"US":{
			"email":"SHUINENGKONGGAO@GMAIL.COM",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"2013SHUINENG",
			"type":"EbatesBuyer"
		},"CA":{
			"email":"SHUINENGDINGZUI@GMAIL.COM",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"SHUINENG",
			"type":"EbatesBuyer"
		},"UK":{
			"email":"SHUINENGKONGGAO@GMAIL.COM",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"2013SHUINENG",
			"type":"EbatesBuyer"
		},"MX":{
			"email":"SHUINENGDINGZUI@GMAIL.COM",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"SHUINENG",
			"type":"EbatesBuyer"
		}
	},
	"giftCardBuyers":{},
	"googledrivebooks":{"US":"https://docs.google.com/spreadsheets/d/1bIhCpweGzkCGvVK6aPiHFs8nPyiLjv66GWSKYJVCNQI/edit#gid=275454052","CA":"https://docs.google.com/spreadsheets/d/1zIK_tCBRvzoquz3fF3RJacf-BKtKnsVzhFH_zFVdgyI/edit?ts=56534620#gid=746644442","UK":"https://docs.google.com/spreadsheets/d/1OJ4ExRVr8_OOetl242qlhPfo23QJ8Lo4a7ou54O2scA/edit#gid=135620489","MX":"https://docs.google.com/spreadsheets/d/17vVIIlnD5BhbAifHuqbxtYVscA9Re-IA-lwzqjNoctA/edit#gid=1159096052"
	},
	"googledriveproducts":{"US":"https://docs.google.com/spreadsheets/d/1bIhCpweGzkCGvVK6aPiHFs8nPyiLjv66GWSKYJVCNQI/edit#gid=275454052","CA":"https://docs.google.com/spreadsheets/d/1uN89VMqUEAIbHZz--JtJdB6Zhvj4a3JmEeaM5I90BNI/edit#gid=512324679","UK":"https://docs.google.com/spreadsheets/d/1hUKxWtIsa1shsFxnSdFFSdAi0ZpTSjA4gmEU2UnTp6s/edit#gid=766692554","MX":"https://docs.google.com/spreadsheets/d/1diKiDlJxE69pgRA0xCML4noXZNsXDGOqU_UUFIAvw2M/edit?ts=56a18511#gid=585449950"
	},
	"id":"25",
	"orderFinders":{"US":"1","CA":"Jessica","UK":"Frank","MX":"Peace"
	},
	"primeBuyers":{"US":{
			"email":"bluelee253@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"lightinhim777153111",
			"type":"PrimeBuyer"
		},"CA":{
			"email":"Christopher64986Apple@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"powerhenwxb",
			"type":"PrimeBuyer"
		},"UK":{
			"email":"fragranceofjesus153@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"jesus153",
			"type":"PrimeBuyer"
		},"MX":{
			"email":"lightgrace456@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"graceishim777",
			"type":"PrimeBuyer"
		}
	},
	"prodPrimeBuyers":{"US":{
			"email":"Christopher64986Apple@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"powerhenwxb",
			"type":"PrimeBuyer"
		},"CA":{
			"email":"Antonio576Alvin@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"jurhrhgfue",
			"type":"PrimeBuyer"
		},"UK":{
			"email":"fragranceofjesus153@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"jesus153",
			"type":"PrimeBuyer"
		},"MX":{
			"email":"Christopher64986Apple@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"powerhenwxb",
			"type":"PrimeBuyer"
		}
	},
	"prodPtBuyers":{"US":{
			"email":"Christopher64986Apple@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"powerhenwxb",
			"type":"PtBuyer"
		},"CA":{
			"email":"lightgrace456@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"graceishim777",
			"type":"PtBuyer"
		},"UK":{
			"email":"fragranceofjesus153@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"jesus153",
			"type":"PtBuyer"
		},"MX":{
			"email":"Christopher64986Apple@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"powerhenwxb",
			"type":"PtBuyer"
		}
	},
	"ptBuyers":{"US":{
			"email":"Christopher64986Apple@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"powerhenwxb",
			"type":"PtBuyer"
		},"CA":{
			"email":"Antonio576Alvin@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"jurhrhgfue",
			"type":"PtBuyer"
		},"UK":{
			"email":"fragranceofjesus153@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"jesus153",
			"type":"PtBuyer"
		},"MX":{
			"email":"greenjoy253@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"becausehimhello144000",
			"type":"PtBuyer"
		}
	},
	"sellerEmails":{"US":{
			"email":"molliebooks@gmail.com",
			"enable2StepVerfication":true,
			"isPrimeAvailable":false,
			"name":"",
			"password":"2012MOLLIE",
			"type":"EmailSender"
		},"CA":{
			"email":"woelxin@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"2012MOLLIE",
			"type":"EmailSender"
		},"UK":{
			"email":"MOLLIEBOOKSUK@GMAIL.COM",
			"enable2StepVerfication":true,
			"isPrimeAvailable":false,
			"name":"",
			"password":"19EEzhufhl0715",
			"type":"EmailSender"
		},"MX":{
			"email":"MOLLIEBOOKSmx@GMAIL.COM",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"2013MOLLIE",
			"type":"EmailSender"
		}
	},
	"sellerids":{"US":"A3TGGH3FFPZNOF/tATVPDKIKX0DER/tAKIAILA6PEIG7VGF3FFQ/tdQ0Eo1mQUBtQcuIRC8HhZ0nY/B8gctrJdP9gFBAC/tMollieBooks/t1.0/tnull","CA":"A1PJZQVQ1OAXTU/tA2EUQ1WTGCTBG2/tAKIAIYTHSU5ZMFOA3J2Q/tq2qiYhfg0kndXNWGm93LJukHy6IET1lndArPDalp/tWoel World/t1.0/tnull","UK":"AOHN76S1YXZGP/tA1F83G8C2ARO7P/tAKIAI66DPK7ZFTG5KSOQ/tdlyveEzsjUtF/SDmrj4Li1LxZhn9bGSKsQO0CO6p/tM&E Store-UK/t1.0/tamzn.mws.46a5561a-a0ff-37e2-c2a9-5ddaba093e1f","MX":"A2KNINL499PLXA/tA1AM78C64UM0Y8/tAKIAIB3PYDQRO625CGXA/tlJeKTAorfhGOfqra5QFclL61Kmz2wXHvBIh4tgpB/tMOLLIE-MX/t1.0/tnull"
	},
	"sellers":{"US":{
			"email":"molliebooks@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"2012MOLLIE",
			"type":"Seller"
		},"CA":{
			"email":"woelxin@gmail.com",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"2012MOLLIE",
			"type":"Seller"
		},"UK":{
			"email":"MOLLIEBOOKSUK@GMAIL.COM",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"2013MOLLIE",
			"type":"Seller"
		},"MX":{
			"email":"MOLLIEBOOKSmx2015@GMAIL.COM",
			"enable2StepVerfication":false,
			"isPrimeAvailable":false,
			"name":"",
			"password":"2015MOLLIE",
			"type":"Seller"
		}
	},
	"signatures":{"US":"Paul","CA":"Jack","UK":"Enoch","MX":"Lily"
	},
	"sortNo":1
}